volumes:
  mysql_db: {}
  postgres_db: {}

services:
  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - type: volume
        source: mysql_db
        target: /var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  postgres:
    image: postgres:17.7
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - type: volume
        source: postgres_db
        target: /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
