services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: narabikae_test
    ports:
      - '3306:3306'

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: narabikae_test
    ports:
      - '5432:5432'
